name: CI Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    types: [closed]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Uncomment code and build
        run: |
          sed -i 's/\/\/ const posts = await fetchLatestPosts();/const posts = await fetchLatestPosts();/' api/rss.js
          npm install
          npm run build

      - name: Commit changes
        run: |
          if git ls-files -o --exclude-standard | grep -q "dist/bundle.js"; then
            git config --local user.email "action@github.com"
            git config --local user.name "GitHub Action"
            git add .
            git add -f dist/bundle.js
            git commit -m "[GitHub Action] Auto build and deploy"
            git push
          else
            echo "Changes detected"
          fi
