name: CI Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    types: [closed]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Uncomment code and build
        run: |
          sed -i 's/\/\/ const posts = await fetchLatestPosts();/const posts = await fetchLatestPosts();/' api/rss.js
          npm install
          npm run build

      - name: Check for changes
        id: check_changes
        run: |
          if git diff-index --quiet HEAD --; then
            echo "No changes to commit"
          else
            echo "Changes detected"
          fi

      - name: Commit changes
        if: steps.check_changes.outputs.stdout == 'Changes detected'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git commit -m "[GitHub Action] Auto build and deploy"
          git push
