name: Uncomment Code on Merge

on:
  push:
    branches: [master]
  pull_request:
    types: [closed]

jobs:
  uncomment-code:
    runs-on: ubuntu-latest
    if: >
      (github.event_name == 'push') ||
      (github.event_name == 'pull_request' && github.event.pull_request.merged == true)

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Uncomment code
        run: sed -i 's/\/\/ const posts = await fetchLatestPosts();/const posts = await fetchLatestPosts();/' index.js

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add index.js
          if git diff-index --quiet HEAD --; then
            echo "No changes to commit"
          else
            git commit -m "[GitHubAction] RSS Feed 불러오는 요청 주석 해제"
            git push
          git push
          fi
