name: Uncomment Code on Merge

on:
  push:
    branches: [master]
  pull_request:
    types: [closed]

jobs:
  uncomment-code:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Uncomment code
        run: sed -i 's/\/\/ const posts = await fetchLatestPosts();/const posts = await fetchLatestPosts();/' api/rss.js

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add api/rss.js
          if git diff-index --quiet HEAD --; then
            echo "No changes to commit"
          else
            git commit -m "[GitHubAction] RSS Feed 불러오는 요청 주석 해제"
            git push
          fi
